theme: jekyll-theme-hacker
show_downloads: false

title: Stuart F Poole | Full-Time Physicist
email: stuart.f.poole@gmail.com
description: Postgraduate physicist at the University of Nottingham
github_username: stupoole
exclude: 
  - Gemfile 
  - Gemfile.lock

url: localhost:4000
baseurl: /
repository: stupoole/stupoole.github.io