theme: jekyll-theme-hacker
show_downloads: false

title: Stuart F Poole | Physicist && Maker
email: stuart.f.poole@gmail.com
description: Postgraduate physicist at The University of Nottingham
github_username: stupoole
author: Stu Poole
exclude: 
  - Gemfile 
  - Gemfile.lock

url: stupoole.github.io
baseurl: /
repository: stupoole/stupoole.github.io