# site settings
title: Stuart Poole
subtitle: Physicist, Maker, Climber
email: stuart.f.poole@gmail.com
description: Postgraduate physicist at The University of Nottingham
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Stu Poole
city: Nottingham
country: United Kingdom
repository: stupoole/stupoole.github.io
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/stupoole
orchid_url: https://orcid.org/0000-0001-7434-8550
linkedin_url: https://www.linkedin.com/in/sfpoole/

# build settings
markdown: kramdown

sass:
  style: compressed
